export const GET_MOVIES = "GET_MOVIES";
export const GET_MOVIE_BY_ID = "GET_MOVIE_BY_ID";
export const GET_MOVIES_BY_TITLE = "GET_MOVIES_BY_TITLE";
export const CLEAN_DETAIL = "CLEAN_DETAIL"
export const GET_GENRES = "GET_GENRES";
export const POST_MOVIE = "POST_MOVIE";
export const DELETE_MOVIE = "DELETE_MOVIE";

export const FILTER_GENRE = "FILTER_GENRE";
export const FILTER_CLASIFICATION = "FILTER_CLASIFICATION";
export const ORDER_ALPHABETIC = "ORDER_ALPHABETIC";
export const ORDER_DATE = "ORDER_DATE";
