//RUTAS MOVIES Y GENERO
export const GET_MOVIES = "GET_MOVIES";
export const GET_MOVIE_BY_ID = "GET_MOVIE_BY_ID";
export const GET_MOVIES_BY_TITLE = "GET_MOVIES_BY_TITLE";
export const CLEAN_DETAIL = "CLEAN_DETAIL";
export const GET_GENRES = "GET_GENRES";

// RUTA DE FILTROS Y ORDENAMIENTOS
export const FILTER_ORDER = "FILTER_ORDER";

// RUTAS DE ADMIN
export const POST_MOVIE = "POST_MOVIE";
export const PUT_MOVIE = "PUT_MOVIE";
export const DELETE_MOVIE = "DELETE_MOVIE";

// RUTAS DE USUARIOS
export const GET_USERS = "GET_USERS";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const POST_USER = "POST_USER";
export const PUT_USER = "PUT_USER";
export const DELETE_USER = "DELETE_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const FORGOT_PASSWORD_USER = "FORGOT_PASSWORD_USER";

// RUTAS DE CANDY
export const GET_CANDY = "GET_CANDY";
export const POST_CANDY = "POST_CANDY";
export const PUT_CANDY = "PUT_CANDY";
export const DELETE_CANDY = "DELETE_CANDY";
export const ADD_TO_CART_CANDY = "ADD_TO_CART_CANDY";
export const REMOVE_ALL_CART_CANDY = "REMOVE_ALL_CART_CANDY";
export const REMOVE_ONE_CANDY = "REMOVE_ONE_CANDY";

// RUTAS DEL CARRITO TICKET
export const POST_ALL_TICKETS = "POST_ALL_TICKETS";
export const ADD_TO_CART = "ADD_TO_CART";
export const SAVE_CART = "SAVE_CART";
export const REMOVE_ALL_CART = "REMOVE_ALL_CART";
export const REMOVE_ONE_CART = "REMOVE_ONE_CART";

// RUTAS SUSCRIPCION
export const PUT_SUBSCRIPTION = "PUT_SUBSCRIPTION";
export const DELETE_SUBSCRIPTION = "DELETE_SUBSCRIPTION";


// RUTAS PURCHASE
export const POST_PURCHASES = "POST_PURCHASES";

// RUTAS RATING
export const POST_RATING = "POST_RATING";